# Generated by Django 5.0.1 on 2024-01-28 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_resume_user_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school',
        ),
    ]
