# Generated by Django 5.0.3 on 2024-05-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='last_response',
            field=models.CharField(blank=True, max_length=20, verbose_name='آخرین پاسخ'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(verbose_name='پیغام'),
        ),
    ]
