# Generated by Django 5.0.3 on 2024-05-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_show_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام شرکت یا سازمان'),
        ),
    ]
