# Generated by Django 5.0.1 on 2024-01-25 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دوره آموزشی')),
                ('description', models.TextField(verbose_name='توشیحات دوره')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع دوره')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ اتمام دوره')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume', verbose_name='رزومه')),
            ],
            options={
                'verbose_name': 'دوره آموزشی',
                'verbose_name_plural': 'دوره های آموزشی',
            },
        ),
        migrations.CreateModel(
            name='ExamWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='عنوان نمونه کار')),
                ('link', models.URLField(blank=True, null=True, verbose_name='آدرس نمونه کار')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume', verbose_name='رزومه')),
            ],
            options={
                'verbose_name': 'نمونه کار',
                'verbose_name_plural': 'نمونه کار ها',
            },
        ),
    ]
