# Generated by Django 5.0.1 on 2024-01-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_courses_examworks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='skill_level',
        ),
        migrations.AddField(
            model_name='courses',
            name='level',
            field=models.CharField(choices=[('a', 'مقدماتی'), ('b', 'متوسط'), ('c', 'پیشرفته')], default='a', max_length=5, verbose_name='سطح دوره'),
        ),
        migrations.AddField(
            model_name='skills',
            name='level',
            field=models.CharField(choices=[('a', 'مقدماتی'), ('b', 'متوسط'), ('c', 'پیشرفته')], default='a', max_length=5, verbose_name='سطح مهارت'),
        ),
    ]
