# Generated by Django 5.0.1 on 2024-01-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_remove_skills_skill_level_courses_level_skills_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی'),
        ),
    ]
