# Generated by Django 5.0.1 on 2024-01-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_resume_active_school_active_school_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='best',
            field=models.BooleanField(default=False, verbose_name='محبوب'),
        ),
    ]
