# Generated by Django 5.0.1 on 2024-01-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_field_best'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='birth_mount',
            field=models.IntegerField(blank=True, null=True, verbose_name='ماه تولد'),
        ),
        migrations.AddField(
            model_name='resume',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='سال تولد'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='birth_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='روز تولد'),
        ),
    ]
