# Generated by Django 5.0.1 on 2024-02-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resume_files/%Y/%m/', verbose_name='فایل رزومه شخصی'),
        ),
    ]
