# Generated by Django 5.0.1 on 2024-03-01 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_alter_resume_about_alter_resume_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.school', verbose_name='هنرستان'),
        ),
    ]
