# Generated by Django 5.0.3 on 2024-03-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_alter_resume_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='birth_day',
            field=models.IntegerField(blank=True, max_length=30, null=True, verbose_name='روز تولد'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='birth_mount',
            field=models.IntegerField(blank=True, max_length=12, null=True, verbose_name='ماه تولد'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='birth_year',
            field=models.IntegerField(blank=True, max_length=1450, null=True, verbose_name='سال تولد'),
        ),
    ]
