# Generated by Django 5.0.3 on 2024-03-13 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0018_alter_resume_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.district', verbose_name='ناحیه محل هنرستان'),
        ),
    ]
