# Generated by Django 5.0.3 on 2024-03-13 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0019_resume_district'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School',
        ),
    ]
