# Generated by Django 5.0.3 on 2024-03-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0021_alter_resume_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='resume_images/%Y/%m/', verbose_name='تصویر'),
        ),
    ]
