# Generated by Django 5.0.3 on 2024-03-17 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0022_resume_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس سایت'),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام زبان')),
                ('level', models.CharField(choices=[('a', 'مقدماتی'), ('b', 'متوسط'), ('c', 'پیشرفته')], default='a', max_length=5, verbose_name='سطح زبان')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume', verbose_name='رزومه')),
            ],
            options={
                'verbose_name': 'زبان',
                'verbose_name_plural': 'زبان ها',
            },
        ),
    ]
