# Generated by Django 5.0.3 on 2024-04-18 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0024_examworks_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.field', verbose_name='رشته'),
        ),
    ]
