# Generated by Django 5.0.3 on 2024-04-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0025_resume_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='examworks',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='زمان بروز رسانی'),
        ),
    ]
